// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsqRH5pIhiVKF_s80f3p_ObeUcDMNNSM',
    appId: '1:858836690099:web:a42509ed671f0db85d3cc6',
    messagingSenderId: '858836690099',
    projectId: 'subscription-based-journal-app',
    authDomain: 'subscription-based-journal-app.firebaseapp.com',
    storageBucket: 'subscription-based-journal-app.firebasestorage.app',
    measurementId: 'G-4N4N1ZEDH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVOajSRT82-GJie5cgrgXJFT_p7_CNXM',
    appId: '1:858836690099:android:d516ce699b81014f5d3cc6',
    messagingSenderId: '858836690099',
    projectId: 'subscription-based-journal-app',
    storageBucket: 'subscription-based-journal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1izD0AS6cHGeXeshb_VaiFLvwYj9T8M',
    appId: '1:858836690099:ios:30dfd05b104143675d3cc6',
    messagingSenderId: '858836690099',
    projectId: 'subscription-based-journal-app',
    storageBucket: 'subscription-based-journal-app.firebasestorage.app',
    iosBundleId: 'com.example.subJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1izD0AS6cHGeXeshb_VaiFLvwYj9T8M',
    appId: '1:858836690099:ios:30dfd05b104143675d3cc6',
    messagingSenderId: '858836690099',
    projectId: 'subscription-based-journal-app',
    storageBucket: 'subscription-based-journal-app.firebasestorage.app',
    iosBundleId: 'com.example.subJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsqRH5pIhiVKF_s80f3p_ObeUcDMNNSM',
    appId: '1:858836690099:web:5b0da4e0e47539895d3cc6',
    messagingSenderId: '858836690099',
    projectId: 'subscription-based-journal-app',
    authDomain: 'subscription-based-journal-app.firebaseapp.com',
    storageBucket: 'subscription-based-journal-app.firebasestorage.app',
    measurementId: 'G-YKQPZ220KF',
  );
}
